services:
  frontend:
    image: blog_tcc_frontend:latest
    container_name: animal_blog_frontend
    ports:
      - "${FRONTEND_PORT:-8001}:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
